import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import Icon from '@/components/Icon';
import DocViewer from '@/components/DocViewer';
import CTA from '@/components/CTA';
import { platforms, getPlatform } from '@/lib/content';

type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return platforms.map(p=>({slug:p.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const p=getPlatform(slug);if(!p)return{};return{title:p.metaTitle,description:p.metaDescription,alternates:{canonical:`/platforms/${p.slug}`},openGraph:{title:p.metaTitle,description:p.metaDescription,type:'website'}};}
export default async function PlatformPage({params}:Props){const {slug}=await params;const p=getPlatform(slug);if(!p)notFound();return <>
<section className="on-dark relative overflow-hidden bg-ink"><div className="shell relative py-16 lg:py-24"><nav className="mb-6"><ol className="flex items-center gap-2 font-mono text-[11px] uppercase tracking-[0.14em] text-ink-mute"><li><Link href="/">Home</Link></li><li>/</li><li><Link href="/platforms">Platforms</Link></li><li>/</li><li className="text-azure-400">{p.name}</li></ol></nav><p className="eyebrow-dark">{p.what}</p><h1 className="mt-4 max-w-4xl font-display text-[34px] font-medium leading-[1.08] tracking-[-0.03em] text-white sm:text-[46px] lg:text-[54px]">{p.h1}</h1><p className="mt-6 max-w-2xl text-[17px] leading-relaxed text-ink-dim">{p.lead}</p><div className="mt-9 flex flex-wrap items-center gap-3"><Link href="/quote" className="btn-primary">Request a quote<Icon name="arrow" className="h-4 w-4"/></Link>{p.docs.length>0&&<a href="#documents" className="btn-ghost-dark">View documents</a>}<span className="font-mono text-[13px] text-azure-400">{p.price}</span></div></div></section>
<section className="shell py-16 lg:py-24"><div className="grid gap-12 lg:grid-cols-[minmax(0,1fr)_320px] lg:gap-16"><div className="space-y-12"><article><h2 className="h-section">What is included</h2><p className="mt-4 max-w-2xl text-[16px] leading-relaxed text-ink/80">{p.name} ships with the operational machinery already built, so the work is configuration and branding rather than development from zero.</p><ul className="mt-6 grid gap-3 sm:grid-cols-2">{p.features.map(x=><li key={x} className="flex gap-3 text-[15px] text-ink/80"><Icon name="check" className="mt-1 h-4 w-4 shrink-0 text-azure-500"/>{x}</li>)}</ul></article><article><h2 className="h-section">Who it suits</h2><p className="mt-4 max-w-2xl text-[16px] leading-relaxed text-ink/80">{p.audience}</p></article>{p.docs.length>0&&<article id="documents"><h2 className="h-section">Platform documents</h2><p className="mt-4 max-w-2xl text-[16px] leading-relaxed text-ink/80">Preview the current specifications and supporting documents.</p><div className="mt-6"><DocViewer docs={p.docs}/></div></article>}{p.faqs.length>0&&<article><h2 className="h-section">Common questions</h2><dl className="mt-6 divide-y divide-paper-edge border-t border-paper-edge">{p.faqs.map(f=><div key={f.q} className="py-5"><dt className="font-display text-[17px]">{f.q}</dt><dd className="mt-2 text-[15px] leading-relaxed text-ink/70">{f.a}</dd></div>)}</dl></article>}</div><aside className="space-y-6 lg:sticky lg:top-24 lg:self-start">{p.deliverables.length>0&&<div className="card"><h2 className="font-display text-[18px]">What you get</h2><ul className="mt-4 space-y-2.5">{p.deliverables.map(d=><li key={d} className="flex gap-2.5 text-[14px] text-ink/75"><Icon name="check" className="mt-0.5 h-4 w-4 shrink-0 text-azure-500"/>{d}</li>)}</ul></div>}<div className="rounded-2xl border border-azure-200 bg-azure-50 p-6"><p className="eyebrow">Starting at</p><p className="mt-2 font-display text-[30px] text-azure-700">{p.price}</p>{p.priceNote&&<p className="mt-1 text-[13px] text-azure-600">{p.priceNote}</p>}<Link href="/quote" className="btn-primary mt-5 w-full">Get a fixed quote</Link></div></aside></div></section><CTA/></>}
